<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Perfil y configuracin_col-s icon</name>
   <tag></tag>
   <elementGuidId>20352c88-976e-4ae6-bd8c-424e09912f6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.a.col-f > div.col-s.icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='region-profile-menu']/div/div[2]/ul/li[4]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-s icon</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-icon</name>
      <type>Main</type>
      <value>off</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;region-profile-menu&quot;)/div[@class=&quot;profile-menu-view&quot;]/div[@class=&quot;drop-down&quot;]/ul[1]/li[@class=&quot;logout&quot;]/div[@class=&quot;a col-f&quot;]/div[@class=&quot;col-s icon&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='region-profile-menu']/div/div[2]/ul/li[4]/div/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/div/div</value>
   </webElementXpaths>
</WebElementEntity>
